// =============================================================================
// texts.ts — TODOS LOS TEXTOS DE LA INTERFAZ, EN ES Y EN
// =============================================================================
// Cada componente pide sus textos con una clave: T[lang].cta1, etc.
// El idioma elegido vive en una cookie ("lang"), así el servidor ya renderiza
// la página en el idioma correcto (ver lib/lang.ts).
// =============================================================================

export type Lang = "es" | "en";

export const T={es:{nHome:"Inicio",nCat:"Catálogo",nBio:"Dante",nCon:"Contacto",bag:"Pedido",
 h1a:"El arte de",h1b:"cantar juntos",
 lead:"321 obras corales de Dante Andreo sobre poesía de García Lorca, Alberti y Pedro García Cabrera. Elegís la partitura, decís cuántas copias necesita tu coro y llega a tu correo.",
 cta1:"Ver el catálogo",cta2:"Quién es Dante",
 fTag:"Del catálogo",fTitle:"Cuatro para empezar",fMore:"Ver las 321 obras",
 sTag:"Cómo funciona",sTitle:"Tres pasos y a ensayar",
 sSub:"No hace falta crear cuenta ni registrarse. El PDF llega al correo apenas se confirma el pago.",
 s1a:"Elegís la obra",s1b:"Filtrás por plantilla, idioma, duración o dificultad, y ves la primera página de la partitura antes de decidir.",
 s2a:"Decís cuántas copias",s2b:"Una por cada cantor de tu coro. El precio por copia baja según la cantidad que lleves.",
 s3a:"Pagás y te llega",s3b:"Con PayPal, en el momento. El PDF entra a tu correo listo para imprimir.",
 licB:"No comprás un archivo, comprás copias autorizadas.",licR:"Cada copia habilita a un cantor. Si tu coro es de 24 personas, comprás 24 copias y podés imprimirlas.",
 bA:"Taller coral",bB:"Dante Andreo trabajando con el coro",
 cTitle:"321 obras esperando un coro",cSub:"Por plantilla, idioma, duración y dificultad. Con la primera página a la vista.",cBtn:"Entrar al catálogo",
 catTag:"Obra completa · 1982—2022",catTitle:"El catálogo",
 catLead:"321 obras para coro. Hacé clic en cualquiera para ver la primera página, los datos y comprarla.",
 ph:"Buscar por título o poeta",allV:"Toda plantilla",
 dur1:"< 2 min",dur2:"2–4 min",dur3:"> 4 min",dif1:"Fácil",dif2:"Media",dif3:"Avanzada",
 niv:"Nivel",filters:"Filtros",done:"Listo",edBadge:"En editorial",extGo:"Ir a la web de la editorial",listenT:"Escuchar y ver",
 works:"obras",none:"Nada con esos filtros",noneP:"Probá aflojar alguno.",reset:"Limpiar todo",
 bTag:"Compositor y director de coro",bTitle:"Dante Andreo",
 bLead:"Cuarenta años escribiendo para coro entre dos orillas: nació en Argentina, vive en España desde 1981, y su música se canta en más de treinta países.",
 tlTag:"La línea de tiempo",whoTag:"Con quiénes trabajó",whoTitle:"Los coros que estrenaron su obra",
 whoSub:"Cada obra del catálogo se estrenó en algún lado, con alguien al frente. Estos son los grupos y los directores que la cantaron primero.",
 edLbl:"Editado por",pzLbl:"Premios",
 cnTag:"Música antigua",cnTitle:"Antes de componer, descifrar",cnCap:"Dante Andreo con un cantoral manuscrito",
 cn1:"Dante se formó en la interpretación de la música antigua española y colonial iberoamericana: manuscritos de archivo, cantorales, obras que llevaban siglos sin sonar.",
 cn2:"Con el Grupo Vocal Gregor llevó ese repertorio a conciertos y grabaciones en más de treinta países de Europa y América.",
 crTag:"El ambiente coral",crTitle:"Cuarenta años de colegas",tbd:"Por identificar",
 rTag:"Escribime",rTitle:"Encargos, talleres y dudas sobre cualquier partitura",
 rLead:"Respondo yo. Si compraste una obra y no te llegó, mandame el número de pedido de PayPal y te la reenvío el mismo día.",
 rights:"Todas las obras están registradas.",
 mVoi:"Plantilla",mPoet:"Texto de",mLang:"Idioma",mDur:"Duración",mYear:"Año",mDif:"Dificultad",
 copies:"¿Cuántas copias?",perS:"Una por cantor",each:"por copia",
 hint:"Precio por copia autorizada. Recibís el PDF por email y podés imprimir esa cantidad.",
 add:"Añadir al pedido",added:"Añadido ✓",
 extT:"Esta obra la edita",extB:"No se vende acá: se consigue en la web de la editorial.",
 empty:"Todavía no elegiste ninguna obra.",items:"obras",cps:"copias",total:"Total",
 pay:"Pagar con PayPal",rm:"Quitar",mailn:"Te mandamos los PDFs apenas se confirme el pago.",yourOrder:"Tu pedido"},
 en:{nHome:"Home",nCat:"Catalogue",nBio:"Dante",nCon:"Contact",bag:"Order",
 h1a:"The art of",h1b:"singing together",
 lead:"321 choral works by Dante Andreo on poetry by García Lorca, Alberti and Pedro García Cabrera. Pick a score, say how many copies your choir needs, and it lands in your inbox.",
 cta1:"See the catalogue",cta2:"Who Dante is",
 fTag:"From the catalogue",fTitle:"Four to start with",fMore:"See all 321 works",
 sTag:"How it works",sTitle:"Three steps and off to rehearsal",
 sSub:"No account, no sign-up. The PDF reaches your inbox as soon as payment clears.",
 s1a:"Pick a work",s1b:"Filter by voicing, language, duration or difficulty, and see the first page of the score before deciding.",
 s2a:"Say how many copies",s2b:"One for each singer in your choir. The price per copy drops with the quantity.",
 s3a:"Pay and receive",s3b:"With PayPal, right away. The PDF arrives ready to print.",
 licB:"You are not buying a file, you are buying authorised copies.",licR:"Each copy covers one singer. If your choir has 24 people, buy 24 copies and print them.",
 bA:"Choral workshop",bB:"Dante Andreo working with the choir",
 cTitle:"321 works waiting for a choir",cSub:"By voicing, language, duration and difficulty. With the first page in view.",cBtn:"Enter the catalogue",
 catTag:"Complete works · 1982—2022",catTitle:"The catalogue",
 catLead:"321 works for choir. Click any of them to see the first page, the details and buy it.",
 ph:"Search by title or poet",allV:"Any voicing",
 dur1:"< 2 min",dur2:"2–4 min",dur3:"> 4 min",dif1:"Easy",dif2:"Intermediate",dif3:"Advanced",
 niv:"Level",filters:"Filters",done:"Done",edBadge:"At publisher",extGo:"Go to the publisher's site",listenT:"Listen and watch",
 works:"works",none:"Nothing matches",noneP:"Try loosening a filter.",reset:"Clear all",
 bTag:"Composer and choral conductor",bTitle:"Dante Andreo",
 bLead:"Forty years writing for choir across two shores: born in Argentina, living in Spain since 1981, his music sung in more than thirty countries.",
 tlTag:"The timeline",whoTag:"Who he worked with",whoTitle:"The choirs that premiered his work",
 whoSub:"Every work in the catalogue was premiered somewhere, with someone in front of it. These are the groups and conductors who sang it first.",
 edLbl:"Published by",pzLbl:"Prizes",
 cnTag:"Early music",cnTitle:"Before composing, deciphering",cnCap:"Dante Andreo with a handwritten choirbook",
 cn1:"Dante trained in the performance of early Spanish and colonial Latin American music: archive manuscripts, choirbooks, works unheard for centuries.",
 cn2:"With the Gregor Vocal Group he took that repertoire to concerts and recordings in more than thirty countries.",
 crTag:"The choral world",crTitle:"Forty years of colleagues",tbd:"To be identified",
 rTag:"Write to me",rTitle:"Commissions, workshops and questions about any score",
 rLead:"I answer personally. If you bought a work and it never arrived, send me the PayPal order number and I resend it the same day.",
 rights:"All works are registered.",
 mVoi:"Voicing",mPoet:"Text by",mLang:"Language",mDur:"Duration",mYear:"Year",mDif:"Difficulty",
 copies:"How many copies?",perS:"One per singer",each:"per copy",
 hint:"Price per authorised copy. You get the PDF by email and may print that many.",
 add:"Add to order",added:"Added ✓",
 extT:"Published by",extB:"Not sold here: available from the publisher's site.",
 empty:"You haven't picked any works yet.",items:"works",cps:"copies",total:"Total",
 pay:"Pay with PayPal",rm:"Remove",mailn:"We email the PDFs as soon as payment clears.",yourOrder:"Your order"}};


export type TextKey = keyof (typeof T)["es"];
